Pubkey use brainpoolP320r1
landgenoot/multichain pull request #2
Opened 2017-05-22 12:50 UTC by klikooo

2017-05-26 09:31 UTC, jonathanraes commented on src/keys/key.cpp
> -    assert(result.IsValid());
asserts may be good to keep in there

2017-05-30 08:25 UTC, jonathanraes approved these changes

2017-05-30 09:32 UTC, wkmeijer requested changes
Since I can't really say much about the functionality of the code because of my lack of Multichain knowledge. I mainly checked for code style and good practice.

I found 4 pieces of commented code that according to me can be removed.

2017-05-30 09:32 UTC, wkmeijer commented on src/keys/key.cpp
> +    //privKey.Initialize( prng, CryptoPP::ASN1::brainpoolP320r1() );
commented code

2017-05-30 09:32 UTC, wkmeijer commented on src/keys/key.cpp
> +        //signature.resize(siglen);
commented code

2017-05-30 09:32 UTC, wkmeijer commented on src/script/interpreter.cpp
> +    //return true;
commented code

2017-05-30 09:32 UTC, wkmeijer commented on src/script/interpreter.cpp
> +        return false;*/
commented code

2017-05-30 09:40 UTC, klikooo commented
Removed the comments

2017-05-30 09:41 UTC, wkmeijer approved these changes

2017-05-30 09:42 UTC, klikooo commented
Creating new PR since this one goes to master

2017-05-30 09:45 UTC, merged